Neos:
  Neos:
    fusion:
      autoInclude:
        Sitegeist.Nomenclator: true

  Flow:
    mvc:
      routes:
        'Sitegeist.Nomenclator':
          position: 'before Neos.Neos'

Sitegeist:
  Nomenclator:
      glossary:
        separator: ','




